version: '3'

services:

  airflow:
    image: apache/airflow:2.9.3
    restart: always

    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./pipeline:/opt/airflow/pipeline

    ports:
      - "8080:8080"

    command: webserver